#!/bin/bash

IFACE="None"
PUB_IP="None"
DEF_GW_ROUTE=`ip -4 route |grep default |wc -l`

if [ "$DEF_GW_ROUTE" -eq 1 ]
  then
    IFACE=`ip -4 route |grep default |cut -d' ' -f5`	  
    LOCAL_IP=`ip -4 -o address show $IFACE |awk '{print $4}' |cut -d '/' -f1 2>/dev/null`
    DIG=`which dig`
    if [ $? -eq 0 ]
       then
          HOST="myip.opendns.com"
          DNS="208.67.222.222"
          OPTIONS="-4 -b $LOCAL_IP +short +tries=1 +retry=0 +timeout=1"
          if [ -z $DNS ]
            then
                DNS=$(resolvectl dns $IFACE |grep -oP "\d+\.\d+\.\d+\.\d+" |head -1)
          fi
          PUB_IP=$($DIG $OPTIONS $HOST @$DNS)
    fi
elif [ "$DEF_GW_ROUTE" -gt 1 ]
   then
      LOCAL_IP="MultiIfaceUP"
elif [ "$DEF_GW_ROUTE" -eq 0 ]
   then
      LOCAL_IP=`ip -o -4 addr show |awk '{if ($2 ~ "^en" || $2 ~ "^wl" || $2 ~ "^eth") print $4} ' |cut -d '/' -f1 |head -n1`
      if [ -z $LOCAL_IP ]
	    then
            LOCAL_IP="LinkDown"
      fi
fi
if [[ ! $PUB_IP =~ ^[0-9] ]]
      then
          PUB_IP="DnsFailure"
fi
echo $PUB_IP-$LOCAL_IP > /tmp/ip_adddresses
